export const upcomingLaunches = [
  {
    slug: "nuvio",
    name: "Nuvio",
    tagline: "Automate your X bio with live metrics",
    author: "Ammar R.",
    category: "Productivity",
    daysAway: 7,
    pledges: 186,
    accent: "from-orange-200 to-rose-200",
  },
  {
    slug: "transcendence",
    name: "Transcendence",
    tagline: "The ultimate Mantra-based meditation timer for iOS",
    author: "Brent Vardy",
    category: "Other",
    daysAway: 47,
    pledges: 78,
    accent: "from-indigo-200 to-sky-200",
  },
  {
    slug: "apyhub",
    name: "ApyHub",
    tagline: "The trusted API ops layer for devs, teams and their agents",
    author: "Nikolas Dimitroulakis",
    category: "Developer Tools",
    daysAway: 13,
    pledges: 71,
    accent: "from-emerald-200 to-teal-200",
  },
  {
    slug: "kempt",
    name: "Kempt",
    tagline: "Home maintenance, on autopilot",
    author: "Brian Garland",
    category: "SaaS",
    daysAway: 21,
    pledges: 71,
    accent: "from-amber-200 to-yellow-200",
  },
  {
    slug: "spendkeep",
    name: "SpendKeep AI",
    tagline: "Privacy-first expense tracking without bank sync",
    author: "Abhistha Chatterjee",
    category: "SaaS",
    daysAway: 14,
    pledges: 64,
    accent: "from-lime-200 to-emerald-200",
  },
  {
    slug: "alsonai",
    name: "AlsonAI",
    tagline: "Stories: created, illustrated, and published with AI",
    author: "faris khan",
    category: "AI",
    daysAway: 3,
    pledges: 52,
    accent: "from-fuchsia-200 to-purple-200",
  },
];

export const pastLaunches = [
  { slug: "glyfiq", name: "Glyfiq", tagline: "Medical & health icon plugin for Figma, Illustrator & Framer", author: "Alex Blogoodf", expected: 136, verified: 133, accent: "from-orange-200 to-amber-200" },
  { slug: "devcleaner", name: "DevCleaner", tagline: "Free the gigabytes your dev tools and AI apps hoard", author: "David Tereba", expected: 89, verified: 88, accent: "from-sky-200 to-blue-200" },
  { slug: "securssh", name: "SecurSSH", tagline: "Team-first SSH access platform", author: "Secure", expected: 89, verified: 85, accent: "from-emerald-200 to-teal-200" },
  { slug: "trestle", name: "Trestle", tagline: "Local secret scanner for AI-assisted development", author: "Radu", expected: 70, verified: 68, accent: "from-rose-200 to-pink-200" },
  { slug: "sulsaly", name: "Sulsaly", tagline: "Agentic AI sales platform built for the Arab world", author: "AR Bites", expected: 59, verified: 58, accent: "from-yellow-200 to-orange-200" },
  { slug: "fireply", name: "Fireply", tagline: "Grow on X. AI agent replies in your voice.", author: "David P", expected: 56, verified: 54, accent: "from-red-200 to-rose-200" },
  { slug: "draftlytic", name: "Draftlytic", tagline: "AI-powered PRD generator for developers", author: "Robert Boylan", expected: 56, verified: 53, accent: "from-violet-200 to-fuchsia-200" },
  { slug: "seaticket", name: "SeaTicket", tagline: "AI agent that resolves issues across all your channels", author: "SeaTicket", expected: 55, verified: 53, accent: "from-cyan-200 to-sky-200" },
  { slug: "reline", name: "Reline", tagline: "AI meeting notes — no bot ever joins your call.", author: "Reline", expected: 53, verified: 53, accent: "from-lime-200 to-green-200" },
];
